### ISSUE TITLE
Improvments

### ISSUE THREAD

**Issue by devmondo** [mdbootstrap/bootstrap-templates#2]
hi, 
may i suggest the following features to make this more beautiful 

-ability to have options to confirm Tag, right now only Enter key is used, we may have space Key and Tab key too
- i have noticed in the  examples if you type a new tag that is not in the source data when Ajax is used as source, you cant enter it, thus will prevent users from adding new values that are not there in the Ajax operation 
- have a minimum characters entered before issuing Ajax to improve performance
  -have a way to validate the tag before approving it
- a way to edit the tag instead of removing it and retyping the desired one, maybe you made spelling mistake, so there is no need to delete, just click on the tag and edit.
  -if user clicks ESC button the entered text should be cleared
  -events on adding, editing, deleting, initializing

thanks in advanced.

**Comment by viral7194** [comment]
hi,

I agreed  regarding to @devmondo  for confirm tag through tab key.. 
it would be great if you introduce tab key in your control 

Thanks in Advanced
