### ISSUE TITLE
Tags Do Not Work With Dynamic Controls

### ISSUE THREAD

**Issue by gordanj** [mdbootstrap/bootstrap-templates#271]
Hello,

I am creating an HTML form on the fly using jquery. If I manually create an input field and give it the "tagsinput" data-role it works awesome. The problem is the tagsinput functionality doesn't work on a dynamically created control. I tried simply moving the taginput JS file to the end of the HTML page in a hope it would run last but that didn't fix my issue. Any suggestions?

Gord

**Comment by NirmalAnandKuzhandaivel** [comment]
Could you please tell me where did u add to get itresolved?

**Comment by gordanj** [comment]
I checked through my code and no longer found a reference to it. Most
likely I had to do whatever I was trying to do differently. Refer to the
refresh section here:
https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

Seems like calling this refresh after the text changes will help. Sorry I
do not have any examples.
