### ISSUE TITLE
How can I use bootstrap-tagsinput on a textarea?

### ISSUE THREAD

**Issue by daviesgeek** [mdbootstrap/bootstrap-templates#38]
I'm trying to use this plugin for a textarea for tagging. How can I use it on a textarea rather than an input?

**Comment by imhussainpatel** [comment]
try this code It will show input as textarea

.tags-input {
      max-width: 100%;
      line-height: 22px;
      overflow-y: scroll;
      overflow-x: scroll;
      height: 65px;
      cursor: text;
 }
