### ISSUE TITLE
Confirm on blur

### ISSUE THREAD

**Issue by haabe** [mdbootstrap/bootstrap-templates#55]
I guess this might not be much of an issue unless you use freeinput.

If a user types in a tag and then clicks outside the input field so that it loses focus, the typed in text is still text. I'd like an option to turn this text into a tag on blur.

An ugly workaround:
$('.bootstrap-tagsinput input').blur(function() {
    $('.myinputfield').tagsinput('add', $(this).val());
    $(this).val('');
});

**Comment by tim-peterson** [comment]
`addOnBlur` should be noted in the documentation as an option.

**Comment by nezirz** [comment]
This worked in my case solution from @itsprdp here:
["https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/236"](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/236)

A better way to clear the typeahead input after adding the tag.

self.$input.typeahead('val', '');

Add this line to the end of the add() function after line number 149 in the src file https://github.com/TimSchlechter/bootstrap-tagsinput/blob/master/src/bootstrap-tagsinput.js

Ref: twitter/typeahead.js#233
