### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by hdattada** [mdbootstrap/bootstrap-templates#571]
I am trying to see if we can use tagsinput with the alpha version of bootstrap4 and it doesn't seem to work. Any idea on how to get around it?

https://v4-alpha.getbootstrap.com

https://jsfiddle.net/hdattada/mh4c8wst/

**Comment by Nodws** [comment]
There ya go 
https://github.com/Nodws/bootstrap-tagsinput

**Comment by DaleMckeown** [comment]
If anyone is interested, I've modified Nodws' css code, turning it into a Sass stylesheet, which can be used with a Sass compiler when building Bootstrap v4.0.0-alpha.6

I've put the code into the following Gist, for anyone to use. Simply use Nodws' Javascript file alongside this.
https://gist.github.com/DaleMckeown/7c24ea66bbd1c04717ca3dada654f8b8

**Comment by SumNeuron** [comment]
@Nodws sorry, but I cant seem to get it to work :/
